[package]
name = "sub"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.0"
actix-files = "0.6.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls", "gzip", "brotli", "deflate", "stream"] }
html-escape = "0.2.13"
regex = "1.12.2"
url = "2.5.7"
toml = "0.9.8"
futures = "0.3.31"
