services:
  sub:
    image: ghcr.io/vansour/sub:latest
    container_name: sub
    hostname: sub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - API=${API:-api}
    restart: unless-stopped
