services:
  sub:
    image: ghcr.io/vansour/sub:latest
    container_name: sub
    hostname: sub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/sub
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: ghcr.io/vansour/postgres:trixie
    container_name: sub-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sub
    volumes:
      - ./pgdata:/var/lib/postgresql
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    dns:
      - '1.1.1.1'