mixed-port: 7890
allow-lan: false
bind-address: "*"
log-level: info
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: []
  use-hosts: false
  use-system-hosts: true
  proxy-server-nameserver:
    - 8.8.8.8
  direct-nameserver:
    - 119.29.29.29
  direct-nameserver-follow-policy: true
  respect-rules: true
  nameserver-policy: {}
proxy-providers:
  {username}:
    type: http
    url: {url}/{username}
    path: ./proxy_providers/{username}.yaml
    interval: 1800
    health-check:
      enable: true
      url: 	http://www.google.com/generate_204
      interval: 300
proxy-groups:
  - name: youtube
    type: select
    use:
      - {username}
  - name: steam
    type: select
    use:
      - {username}
  - name: hk
    type: select
    use:
      - {username}
  - name: fallback
    type: select
    use:
      - {username}
rule-providers:
  ipcidr_cn:
    type: http
    behavior: ipcidr
    url: https://gh-proxy.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/ip/cn.yaml
    path: ./rule_providers/ipcidr_cn.yaml
    interval: 86400
  domain_cn:
    type: http
    behavior: domain
    url: https://gh-proxy.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/cn.yaml
    path: ./rule_providers/domain_cn.yaml
    interval: 86400
  domain_steam:
    type: http
    behavior: domain
    url: https://gh-proxy.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/steam.yaml
    path: ./rule_providers/domain_steam.yaml
    interval: 86400
  domain_youtube:
    type: http
    behavior: domain
    url: https://gh-proxy.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/youtube.yaml
    path: ./rule_providers/domain_youtube.yaml
    interval: 86400
  domain_hk:
    type: http
    behavior: domain
    url: https://gh-proxy.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/hk.yaml
    path: ./rule_providers/domain_hk.yaml
    interval: 86400
rules:
  - RULE-SET,ipcidr_cn,DIRECT
  - RULE-SET,domain_cn,DIRECT
  - RULE-SET,domain_steam,steam
  - RULE-SET,domain_youtube,youtube
  - RULE-SET,domain_hk,hk
  - MATCH,fallback
